services:
  cratos-ui:
    build:
      context: .
      args:
        - VITE_SCHEDULER_API_URL=${VITE_SCHEDULER_API_URL:-http://localhost:8001}
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    container_name: cratos-ui
    extra_hosts:
      - 'host.docker.internal:host-gateway'

networks:
  cratos-ui-network:
    external: false
